#!/bin/bash
# Project: Crankshaft
# This file is part of Crankshaft project.
# Copyright (C) 2025 OpenCarDev Team
#
#  Crankshaft is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Crankshaft is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Crankshaft. If not, see <http://www.gnu.org/licenses/>.

set -e

# Pre-removal script for crankshaft-slim-ui

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            echo "Stopping crankshaft-slim-ui service..."
            systemctl stop crankshaft-slim-ui.service || true
            
            if [ "$1" = "remove" ]; then
                echo "Disabling crankshaft-slim-ui service..."
                systemctl disable crankshaft-slim-ui.service || true
            fi
        fi
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
